version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: italia_bez_problem_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always

  web:
    build: .
    command: gunicorn italia_bez_problem.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/italia_bez_problem_db
      DJANGO_SETTINGS_MODULE: italia_bez_problem.settings
      SECRET_KEY: your_super_secret_key_here
      DEBUG: "True"
    restart: always 

volumes:
  postgres_data:
  media_volume:
