# Generated by Django 5.2.4 on 2025-07-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('name_it', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('slogan_en', models.CharField(max_length=255, null=True, verbose_name='Slogan')),
                ('slogan_ru', models.CharField(max_length=255, null=True, verbose_name='Slogan')),
                ('slogan_it', models.CharField(max_length=255, null=True, verbose_name='Slogan')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('address_it', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('working_hours_mon_fri', models.CharField(default='9-13:00 15:00-18:00', max_length=100, verbose_name='Working Hours (Mon-Fri)')),
                ('working_hours_mon_fri_en', models.CharField(default='9-13:00 15:00-18:00', max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)')),
                ('working_hours_mon_fri_ru', models.CharField(default='9-13:00 15:00-18:00', max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)')),
                ('working_hours_mon_fri_it', models.CharField(default='9-13:00 15:00-18:00', max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)')),
                ('working_hours_sat', models.CharField(default='9:00-13:00', max_length=100, verbose_name='Working Hours (Saturday)')),
                ('working_hours_sat_en', models.CharField(default='9:00-13:00', max_length=100, null=True, verbose_name='Working Hours (Saturday)')),
                ('working_hours_sat_ru', models.CharField(default='9:00-13:00', max_length=100, null=True, verbose_name='Working Hours (Saturday)')),
                ('working_hours_sat_it', models.CharField(default='9:00-13:00', max_length=100, null=True, verbose_name='Working Hours (Saturday)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
                ('clients_count', models.IntegerField(default=5000, verbose_name='Number of Served Clients')),
                ('about_us_short', models.TextField(help_text='Used on homepage', verbose_name='Short About Us Description')),
                ('about_us_short_en', models.TextField(help_text='Used on homepage', null=True, verbose_name='Short About Us Description')),
                ('about_us_short_ru', models.TextField(help_text='Used on homepage', null=True, verbose_name='Short About Us Description')),
                ('about_us_short_it', models.TextField(help_text='Used on homepage', null=True, verbose_name='Short About Us Description')),
                ('about_us_full', models.TextField(help_text='Used on About Us page', verbose_name='Full About Us Description')),
                ('about_us_full_en', models.TextField(help_text='Used on About Us page', null=True, verbose_name='Full About Us Description')),
                ('about_us_full_ru', models.TextField(help_text='Used on About Us page', null=True, verbose_name='Full About Us Description')),
                ('about_us_full_it', models.TextField(help_text='Used on About Us page', null=True, verbose_name='Full About Us Description')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Mission')),
                ('mission_en', models.TextField(blank=True, null=True, verbose_name='Mission')),
                ('mission_ru', models.TextField(blank=True, null=True, verbose_name='Mission')),
                ('mission_it', models.TextField(blank=True, null=True, verbose_name='Mission')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Vision')),
                ('vision_en', models.TextField(blank=True, null=True, verbose_name='Vision')),
                ('vision_ru', models.TextField(blank=True, null=True, verbose_name='Vision')),
                ('vision_it', models.TextField(blank=True, null=True, verbose_name='Vision')),
                ('homepage_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Homepage Video (MP4)')),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Service Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Service Title')),
                ('title_it', models.CharField(max_length=200, null=True, verbose_name='Service Title')),
                ('short_description', models.TextField(help_text='Used for cards', verbose_name='Short Description')),
                ('short_description_en', models.TextField(help_text='Used for cards', null=True, verbose_name='Short Description')),
                ('short_description_ru', models.TextField(help_text='Used for cards', null=True, verbose_name='Short Description')),
                ('short_description_it', models.TextField(help_text='Used for cards', null=True, verbose_name='Short Description')),
                ('full_description', models.TextField(help_text='Used on service details page', verbose_name='Full Description')),
                ('full_description_en', models.TextField(help_text='Used on service details page', null=True, verbose_name='Full Description')),
                ('full_description_ru', models.TextField(help_text='Used on service details page', null=True, verbose_name='Full Description')),
                ('full_description_it', models.TextField(help_text='Used on service details page', null=True, verbose_name='Full Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (EUR)')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name="Icon Class (e.g., 'fas fa-briefcase')")),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('full_name_en', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('full_name_it', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('position_it', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('experience_en', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('experience_ru', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('experience_it', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Photo')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
