# Generated by Django 5.2.4 on 2025-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Link'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number (e.g., +1234567890)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_us_short',
            field=models.CharField(help_text='Used on homepage', max_length=300, verbose_name='Short About Us Description'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_us_short_en',
            field=models.CharField(help_text='Used on homepage', max_length=300, null=True, verbose_name='Short About Us Description'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_us_short_it',
            field=models.CharField(help_text='Used on homepage', max_length=300, null=True, verbose_name='Short About Us Description'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_us_short_ru',
            field=models.CharField(help_text='Used on homepage', max_length=300, null=True, verbose_name='Short About Us Description'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='clients_count',
            field=models.IntegerField(default=0, verbose_name='Number of Served Clients'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(default='', verbose_name='Mission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission_it',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission_ru',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(default='', verbose_name='Vision'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision_en',
            field=models.TextField(null=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision_it',
            field=models.TextField(null=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision_ru',
            field=models.TextField(null=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_mon_fri',
            field=models.CharField(max_length=100, verbose_name='Working Hours (Mon-Fri)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_mon_fri_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_mon_fri_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_mon_fri_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Mon-Fri)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_sat',
            field=models.CharField(max_length=100, verbose_name='Working Hours (Saturday)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_sat_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Saturday)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_sat_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Saturday)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_hours_sat_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Working Hours (Saturday)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Used for cards', max_length=300, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(help_text='Used for cards', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_it',
            field=models.CharField(help_text='Used for cards', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_ru',
            field=models.CharField(help_text='Used for cards', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
    ]
